version: "3.9"

services:
  mongodb:
    image: mongo:latest
    container_name: mongodb
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
      MONGO_INITDB_DATABASE: admin
    volumes:
      - mongo_data1:/data/db
  mongodb2:
    image: mongo:latest
    container_name: mongodb2
    ports:
      - 27018:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
      MONGO_INITDB_DATABASE: admin
    volumes:
      - type: volume
        source: mongo_data2
        target: /data/db
        read_only: false

volumes:
  mongo_data1:
    name: mongo_data1
  mongo_data2:
    name: mongo_data2