version: "3.8"

services:
  app:
    container_name: app
    build:
      context: "./build"
      dockerfile: Dockerfile
    image: "app-golang:1.0.0"
    environment:
      - "PORT=8080"
    ports:
      - "8080:8080"